macro(target_enable_cpplatest project)
	if(MSVC)
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /std:c++latest")
	else(MSVC)
		target_compile_features(${project} PRIVATE cxx_std_17)
	endif(MSVC)
endmacro()
